version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      pg_host: postgres
      pg_port: 5432
      pd_database: islab1
      pg_username: postgres
      pg_password: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_DB: islab1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
